language: ruby

jobs:
  include:
    # - os: linux
    #   arch: amd64
    #   dist: focal
    #   rvm: 2.5
    # - os: linux
    #   arch: amd64
    #   dist: focal
    #   rvm: 2.6
    # - os: linux
    #   arch: amd64
    #   dist: focal
    #   rvm: 2.7
    # - os: linux
    #   arch: arm64
    #   dist: focal
    # - os: osx
    #   arch: amd64
    #   osx_image: xcode12.2
    #   rvm: 2.5
    # - os: osx
    #   arch: amd64
    #   osx_image: xcode12.2
    #   rvm: 2.6
    # - os: osx
    #   arch: amd64
    #   osx_image: xcode12.2
    #   rvm: 2.7
    - os: windows
      arch: amd64
      language: bash
      before_install:
        - choco uninstall mingw
        - choco upgrade msys2 ruby zstandard
        - ridk.cmd exec pacman --sync --noconfirm --needed make
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-crt-git
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gcc-libs
            mingw-w64-x86_64-headers-git
            mingw-w64-x86_64-libwinpthread-git
            mingw-w64-x86_64-winpthreads-git

addons:
  apt:
    packages:
      - libzstd-dev
  homebrew:
    packages:
      - zstd

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh

after_success:
  - bash <(curl -s "https://codecov.io/bash")
