language: ruby
rvm:
  - 2.7

os:
  - linux
  - osx

dist: bionic
osx_image: xcode11.2

arch:
  - amd64
  - arm64

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh

after_success:
  - bash <(curl -s "https://codecov.io/bash")
