language: ruby
rvm:
  - 2.7

dist: bionic
osx_image: xcode11.2

jobs:
  include:
    - os: linux
      arch: amd64
    - os: osx
      arch: amd64

before_install:
  - gem install bundler

script:
  - scripts/ci_test.sh

after_success:
  - bash <(curl -s "https://codecov.io/bash")
